-- =============================================================================
-- Seed: hospitais parceiros a partir da lista `hospital_origem` do Chatwoot (ago/2026)
-- Idempotente (compara por nome, sem diferenciar maiúsculas). Não apaga nada.
-- 258 nomes; ignorados os marcadores: Origem Residência com Contato Comercial, Origem Residência sem Contato Comercial, Saúde Mental Adulto, Saúde Mental Infantojuvenil.
-- =============================================================================
CREATE UNIQUE INDEX IF NOT EXISTS uq_hospitais_nome ON public.hospitais (lower(trim(nome)));
INSERT INTO public.hospitais (nome)
SELECT v.nome FROM (VALUES
  ('Hospital das Clínicas Luiza de Pinho Melo'),
  ('Hospital Santa Casa e Fundação Regional de Misericórdia de Bragança Paulista'),
  ('AMA Parque Fernanda'),
  ('CAISM Unifesp SPDM'),
  ('Centro Hospitalar de Santo André - CHMSA'),
  ('Centro Médico 24 Horas Amil'),
  ('Centro Médico de Campinas'),
  ('Centro Terapêutico Sonho de Vida'),
  ('Clínica de Recuperação Hanover'),
  ('Clínica Erimus'),
  ('Clínica Hamabe Prime'),
  ('Clínica Maia'),
  ('Clínica Viv - Vila Verde, Minas Gerais'),
  ('Clínica Viv - Embu das Artes'),
  ('Espaço Amil Saúde Tatuapé'),
  ('FOCOH'),
  ('GPACI - Grupo de Pesquisa e Assistência ao Câncer Infantil'),
  ('Hospitais Family'),
  ('Hospital Cruz Azul'),
  ('Hospital Doutor Arthur Ribeiro de Saboya'),
  ('Hospital Itatiba'),
  ('Hospital São Miguel'),
  ('Hospital 10 de Julho de Pindamonhangaba'),
  ('Hospital 12 de Outubro (Hospital da Criança)'),
  ('Hospital Adventista Aclimação'),
  ('Hospital Adventista Capão Redondo'),
  ('Hospital Adventista Liberdade'),
  ('Hospital Albert Einstein Chácara Klabin'),
  ('Hospital Albert Sabin'),
  ('Hospital Albert Sabin Lapa'),
  ('Hospital Alpha Med'),
  ('Hospital Alvorada'),
  ('Hospital Alvorada Américas'),
  ('Hospital Alvorada Moema'),
  ('Hospital Ana Costa Santos'),
  ('Hospital André Sacco'),
  ('Hospital Assunção'),
  ('Hospital Avicena'),
  ('Hospital Bartira'),
  ('Hospital Beneficência Portuguesa de São Paulo'),
  ('Hospital Beneficência Portuguesa São Caetano'),
  ('Hospital Beneficência Portuguesa de Santo André'),
  ('Hospital Bosque da Saúde'),
  ('Hospital Brás Cubas'),
  ('Hospital Brasil Santo André'),
  ('Hospital Caieiras'),
  ('Hospital Campo Limpo'),
  ('Hospital Carlos Chagas'),
  ('Hospital Celso Pierro'),
  ('Hospital Central de Guaianazes'),
  ('Hospital Central Leste'),
  ('Hospital Central Oeste'),
  ('Hospital Central Sul (Antigo Serra Mayor)'),
  ('Hospital Central Tatuapé'),
  ('Hospital Cesário Lange'),
  ('Hospital Christovão da Gama'),
  ('Hospital Cruzeiro do Sul'),
  ('Hospital da Luz - Butantã'),
  ('Hospital da Luz - Santo Amaro'),
  ('Hospital da Luz - Vila Mariana'),
  ('Hospital de Clínicas Antônio Afonso'),
  ('Hospital de Ribeirão Pires'),
  ('Hospital Dom Alvarenga'),
  ('Hospital Doutor Christovão da Gama'),
  ('Hospital e Maternidade Brasil'),
  ('Hospital e Maternidade Dois Pinheiros'),
  ('Hospital e Maternidade Independência'),
  ('Hospital e Maternidade Ipiranga'),
  ('Hospital e Maternidade Ipiranga Arujá'),
  ('Hospital Edmundo Vasconcelos'),
  ('Hospital Einstein Ibirapuera'),
  ('Hospital Evangélico de Sorocaba'),
  ('Hospital Francisca Julia'),
  ('Hospital Galileo'),
  ('Hospital Geral de Itapecerica da Serra'),
  ('Hospital Hapvida Sorocaba'),
  ('Hospital HCor'),
  ('Hospital Heliópolis'),
  ('Hospital Hospitalis Barueri'),
  ('Hospital HSANP'),
  ('Hospital Igesp'),
  ('Hospital Infantil Gonzaga'),
  ('Hospital Ipiranga Mogi das Cruzes'),
  ('Hospital Irmãs Hospitaleiras'),
  ('Hospital Israelita Albert Einstein Morumbi'),
  ('Hospital Israelita Albert Einstein Perdizes'),
  ('Hospital Itacolomy Butantã'),
  ('Hospital Itaim'),
  ('Hospital Jardim Iva'),
  ('Hospital Le Forte - Liberdade'),
  ('Hospital Le Forte - Morumbi'),
  ('Hospital Madre Teodora'),
  ('Hospital Mandaqui'),
  ('Hospital Mater Dei, Minas Gerais'),
  ('Hospital M''Boi Mirim'),
  ('Hospital Metropolitano'),
  ('Hospital Moriah'),
  ('Hospital Municipal da Criança e do Adolescente'),
  ('Hospital Municipal de Cajamar'),
  ('Hospital Municipal de Parelheiros'),
  ('Hospital Municipal de Urgências de Guarulhos'),
  ('Hospital Municipal Dr. Benedicto Montenegro'),
  ('Hospital Municipal, Minas Gerais'),
  ('Hospital Nipo-Brasileiro'),
  ('Hospital Nossa Senhora do Rosário'),
  ('Hospital Notre Care'),
  ('Hospital Notre Dame Intermédica Guarulhos'),
  ('Hospital Notre Dame Intermédica Osasco'),
  ('Hospital Notre Care Sorocaba'),
  ('Hospital Nova Med Saúde'),
  ('Hospital Nova Vida Itapevi'),
  ('Hospital Nove de Julho'),
  ('Hospital Nove de Julho Alphaville'),
  ('Hospital Nove de Julho Jardim Paulista'),
  ('Hospital Novo Atibaia'),
  ('Hospital Oeste D''Or'),
  ('Hospital Oswaldo Cruz'),
  ('Hospital Paulistano'),
  ('Hospital Paulo Sacramento'),
  ('Hospital Pitangueiras'),
  ('Hospital Pitangueiras Jundiaí'),
  ('Hospital Policlim'),
  ('Hospital Portinari'),
  ('Hospital Pró-Infância São José'),
  ('Hospital Pró-Matre'),
  ('Hospital Pronto Atendimento Municipal Jardim Macedônia'),
  ('Hospital Psiquiátrico API'),
  ('Hospital Regional de Taubaté'),
  ('Hospital Regional do Vale do Paraíba'),
  ('Hospital Ribeirão Gomes'),
  ('Hospital Sabará'),
  ('Hospital Saint Nicholas'),
  ('Hospital Salvalus'),
  ('Hospital Samaritano'),
  ('Hospital Samaritano Hortolândia'),
  ('Hospital Sancta Maggiore Alto da Lapa'),
  ('Hospital Sancta Maggiore Alto da Mooca'),
  ('Hospital Sancta Maggiore Butantã'),
  ('Hospital Sancta Maggiore Dubai'),
  ('Hospital Sancta Maggiore Jardim Paulista'),
  ('Hospital Sancta Maggiore Madri'),
  ('Hospital Sancta Maggiore Mooca'),
  ('Hospital Sancta Maggiore Nápoles'),
  ('Hospital Sancta Maggiore Santana'),
  ('Hospital Sancta Maggiore São Bernardo'),
  ('Hospital Sancta Maggiore Tatuapé'),
  ('Hospital Santa Catarina Paulista'),
  ('Hospital Santa Clara'),
  ('Hospital Santa Cruz'),
  ('Hospital Santa Elisa'),
  ('Hospital Santa Helena'),
  ('Hospital Santa Inês'),
  ('Hospital Santa Isabel'),
  ('Hospital Santa Joana'),
  ('Hospital Santa Marcelina Itaquera'),
  ('Hospital Santa Marcelina São Bernardo'),
  ('Hospital Santa Maria de Suzano'),
  ('Hospital Santa Paula'),
  ('Hospital Santa Rita'),
  ('Hospital Santa Rosa, Mato Grosso'),
  ('Hospital Santa Virgínia'),
  ('Hospital Santana de Mogi'),
  ('Hospital São Bernardo'),
  ('Hospital São Camilo - Ipiranga'),
  ('Hospital São Camilo - Pompeia'),
  ('Hospital São Camilo - Santana'),
  ('Hospital São Cristóvão'),
  ('Hospital São Francisco Cotia'),
  ('Hospital São Luís Alphaville'),
  ('Hospital São Luís Itaim'),
  ('Hospital São Luís Villa-Lobos'),
  ('Hospital São Luiz Morumbi'),
  ('Hospital São Luiz Anália Franco'),
  ('Hospital São Luiz Guarulhos'),
  ('Hospital São Luiz Jabaquara'),
  ('Hospital São Luiz Osasco'),
  ('Hospital São Luiz São Bernardo do Campo'),
  ('Hospital São Luiz São Caetano do Sul'),
  ('Hospital São Paulo Araraquara'),
  ('Hospital São Vicente de Paulo'),
  ('Hospital Saúde Premium'),
  ('Hospital Sepaco'),
  ('Hospital Sepaco Mogi'),
  ('Hospital Sírio-Libanês'),
  ('Hospital UMS Jequitibá'),
  ('Hospital Unidade Avançada Amil Luz Butantã'),
  ('Hospital Unidade Avançada Amil Santo Amaro'),
  ('Hospital Unimed de América'),
  ('Hospital Unimed Guarulhos'),
  ('Hospital Unimed Registro'),
  ('Hospital Unimed Sudoeste'),
  ('Hospital Vera Cruz'),
  ('Hospital Vera Cruz de Campinas'),
  ('Hospital Vidas'),
  ('Hospital Vila Nova Star'),
  ('Hospital Villa-Lobos'),
  ('Hospital Vitória Américas Serviços Médicos'),
  ('Hospital Vitória Anália Franco'),
  ('Hospital Vivalle'),
  ('Hospital Yes'),
  ('Innova Hospitais'),
  ('Outro Serviço Psiquiátrico'),
  ('PPA - Projeto Pró-Autista'),
  ('Prime House'),
  ('Pronto Atendimento Cohab II'),
  ('Pronto Atendimento de Mairinque'),
  ('Pronto Atendimento Unimed Campinas'),
  ('Pronto Atendimento Unimed Jundiaí'),
  ('Pronto Socorro e Maternidade Nair Fonseca'),
  ('Pronto Socorro Municipal de Porto Feliz'),
  ('Pronto Socorro Taminato'),
  ('Pronto Socorro Unimed Vale Novo Paulista'),
  ('PS e Maternidade Nair Fonseca Leitão Arantes'),
  ('Pronto Socorro Central de Embu das Artes'),
  ('SAMEB'),
  ('Santa Casa de Misericórdia de Jacareí'),
  ('Santa Casa de Misericórdia de São Paulo'),
  ('Santa Casa de São Bernardo'),
  ('Santa Casa de São José dos Campos'),
  ('Santa Casa de São Manuel'),
  ('Santa Casa de Saúde'),
  ('Santa Casa de Saúde de Santos'),
  ('Santa Casa de Vinhedo'),
  ('São Joaquim Hospital e Maternidade'),
  ('Unimed Americana'),
  ('UPA - Pronto Atendimento Vila Luzita'),
  ('UPA 21 de Junho'),
  ('UPA Akira'),
  ('UPA Campo dos Alemães'),
  ('UPA Campo Limpo'),
  ('UPA Carrão'),
  ('UPA City'),
  ('UPA Cumbica'),
  ('UPA Dona Maria Antonieta'),
  ('UPA Dr. Atualpa Girão Rabelo'),
  ('UPA Dra. Zilda Arns'),
  ('UPA Francisco Morato'),
  ('UPA Jabaquara'),
  ('UPA Jaçanã'),
  ('UPA Lapa'),
  ('UPA Mauá'),
  ('UPA Parelheiros'),
  ('UPA Perus'),
  ('UPA Pirituba'),
  ('UPA Rio Grande da Serra'),
  ('UPA Sacadura Cabral'),
  ('UPA Sacomã'),
  ('UPA Santa Luzia Ribeirão Pires'),
  ('UPA Santo Amaro'),
  ('UPA São Caetano'),
  ('UPA Taboão'),
  ('UPA Tatuapé'),
  ('UPA Tito Lopes'),
  ('UPA Vergueiro'),
  ('UPA Vila Santa Catarina'),
  ('UPA Vinte e Um de Junho'),
  ('UPA Zona Leste'),
  ('Vindo de Outro Serviço Psiquiátrico - API')
) AS v(nome)
WHERE NOT EXISTS (SELECT 1 FROM public.hospitais h WHERE lower(trim(h.nome)) = lower(trim(v.nome)));
